baseURL = "https://liangjinzhi.com/"
defaultContentLanguage = "zh-cn"
locale = "zh-cn"
title = "\u6211\u7684\u4e2a\u4eba\u535a\u5ba2"
theme = "hugo-book"
publishDir = "docs"
ignoreLogs = ['warning-goldmark-raw-html'] # 顺便隐藏那个 raw-html 警告

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许渲染 Markdown 文章里的 HTML 标签（解决正文空白问题）
      
[params]
  env = "production"
  title = "我的个人博客"
  digestInHTML = false # 关闭指纹校验，防止 CSS 渲染失败
  BookSection = 'posts' # <--- 加上这一行，指定读取 content/posts 目录

