baseURL = "https://liangjinzhi.com/"
defaultContentLanguage = "zh-cn"
locale = "zh-cn"
title = "梁锦志 | 运维与开发笔记"
theme = "PaperMod"
publishDir = "docs"

# Generate JSON index for search.
[outputs]
  home = ["HTML", "JSON"]

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "index"
  isPlainText = true

[params]
  mainSections = ["posts"]
  digestInHTML = false

[params.sidebar]
  emoji = "👋"
  subtitle = "记录运维与开发的笔记"
  avatar = "/img/avatar.png"
  avatarLink = "/posts/about-author/"
  widgets = ["search", "archives", "categories", "tags", "recent_posts"]

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "about"
  name = "关于作者"
  url = "/posts/about-author/"
  weight = 20

[params.sidebar.search]
  enable = true

[params.colorScheme]
  toggle = false
  default = "light"

[params.comments]
  enabled = false